"""initial_schema

Revision ID: 39fc150e3505
Revises: 
Create Date: 2026-03-05 12:48:09.563395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '39fc150e3505'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_call_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('date_utc', sa.Date(), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint', 'date_utc', name='uq_endpoint_date')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('profiling', 'planning', 'generating', 'pending_approval', 'approved', 'executing', 'monitoring', 'optimizing', 'completed', 'rejected', name='campaignstatus'), nullable=False),
    sa.Column('state_checkpoint', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rejection_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_profiles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('marital_status', sa.String(), nullable=True),
    sa.Column('family_size', sa.Integer(), nullable=True),
    sa.Column('dependent_count', sa.Integer(), nullable=True),
    sa.Column('kids_in_household', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('occupation_type', sa.String(), nullable=True),
    sa.Column('monthly_income', sa.Integer(), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('kyc_status', sa.String(), nullable=True),
    sa.Column('app_installed', sa.String(), nullable=True),
    sa.Column('existing_customer', sa.String(), nullable=True),
    sa.Column('social_media_active', sa.String(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('segment_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_profiles_customer_id'), 'customer_profiles', ['customer_id'], unique=True)
    op.create_table('agent_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('campaign_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_logs_campaign_id'), 'agent_logs', ['campaign_id'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('campaign_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('customer_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('send_time', sa.String(), nullable=True),
    sa.Column('predicted_open_rate', sa.Float(), nullable=True),
    sa.Column('predicted_click_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segments_campaign_id'), 'segments', ['campaign_id'], unique=False)
    op.create_table('variants',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('segment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('external_campaign_id', sa.String(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('has_emoji', sa.Boolean(), nullable=True),
    sa.Column('has_url', sa.Boolean(), nullable=True),
    sa.Column('font_styles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('open_count', sa.Integer(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variants_segment_id'), 'variants', ['segment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variants_segment_id'), table_name='variants')
    op.drop_table('variants')
    op.drop_index(op.f('ix_segments_campaign_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_agent_logs_campaign_id'), table_name='agent_logs')
    op.drop_table('agent_logs')
    op.drop_index(op.f('ix_customer_profiles_customer_id'), table_name='customer_profiles')
    op.drop_table('customer_profiles')
    op.drop_table('campaigns')
    op.drop_table('api_call_logs')
    # ### end Alembic commands ###
